[target.x86_64-unknown-linux-gnu]
linker = "./script/zig/cc-x86_64-linux-gnu"

[target.x86_64-unknown-linux-musl]
linker = "./script/zig/cc-x86_64-linux-musl"

[target.aarch64-unknown-linux-gnu]
linker = "./script/zig/cc-aarch64-linux-gnu"

[target.aarch64-unknown-linux-musl]
linker = "./script/zig/cc-aarch64-linux-musl"

[target.x86_64-pc-windows-gnu]
linker = "./script/zig/cc-x86_64-windows-gnu"

[target.aarch64-pc-windows-msvc]
linker = "./script/zig/cc-aarch64-windows-msvc"

[target.x86_64-apple-darwin]
linker = "./script/zig/cc-x86_64-macos"

[target.aarch64-apple-darwin]
linker = "./script/zig/cc-aarch64-macos"
